name: cocogitto

on: [pull_request]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check commits with cocogitto
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # pick the pr HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Conventional commits compliance check
        uses: oknozor/cocogitto-action@v3
        with:
          check-latest-tag-only: true
          git-user: 'yoctoyotta1024'
          git-user-email: 'yoctoyotta1024@yahoo.com'
