name: cocogitto

on: [push]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check commits with cocogitto
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional commits compliance check
        uses: oknozor/cocogitto-action@v3
        with:
          check-latest-tag-only: true
          git-user: 'yoctoyotta1024'
          git-user-email: 'yoctoyotta1024@yahoo.com'

  release:
    needs: cog_check_job
    # Only release new version when merging into `origin/main`.`
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'yoctoyotta1024'"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true
          git-user: 'yoctoyotta1024'
          git-user-email: 'yoctoyotta1024@yahoo.com'

      # The version number is accessible as a github action output
      - name: Print version
        run: "echo '${{ steps.release.outputs.version }}'"
